{
  "host": "api.sencrop.com",
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Sencrop API",
    "description": "API to consume Sencrop data"
  },
  "basePath": "/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/ping": {
      "get": {
        "operationId": "getPing",
        "summary": "Checks API's availability.",
        "tags": [
          "system"
        ]
      }
    },
    "/crops": {
      "get": {
        "operationId": "getCrops",
        "summary": "Get the crops",
        "tags": []
      }
    },
    "/modules": {
      "get": {
        "operationId": "getModules",
        "summary": "Get the modules",
        "tags": []
      }
    },
    "/utils/checkSignup": {
      "post": {
        "operationId": "postSignupCheck",
        "summary": "Hit the server to check the email can be used to signup.",
        "tags": []
      }
    },
    "/password/lost": {
      "post": {
        "operationId": "postLostPassword",
        "summary": "Request a password change e-mail.",
        "tags": []
      }
    },
    "/password": {
      "put": {
        "operationId": "putPassword",
        "summary": "Change a user password",
        "tags": []
      }
    },
    "/users/sign_in": {
      "post": {
        "operationId": "postLogin",
        "summary": "Log a user in",
        "tags": []
      }
    },
    "/users/verify": {
      "post": {
        "operationId": "postVerify",
        "summary": "Verify a user",
        "tags": []
      }
    },
    "/partners/{partnerId}/tokenRequests": {
      "post": {
        "operationId": "postPartnerTokenRequest",
        "summary": "Request a user token",
        "tags": [
          "partners"
        ],
        "security": [
          {
            "basicAuth": [
              "ROLE_PARTNER"
            ]
          }
        ]
      }
    },
    "/partners/{partnerId}/tokens": {
      "post": {
        "operationId": "postPartnerToken",
        "summary": "Create a user token",
        "tags": [
          "partners"
        ],
        "security": [
          {
            "basicAuth": [
              "ROLE_PARTNER"
            ]
          }
        ]
      }
    },
    "/partners/{partnerId}/devices": {
      "get": {
        "operationId": "getPartnerDevices",
        "summary": "Retrieves the devices a partner has access to.",
        "tags": [
          "partners"
        ],
        "security": [
          {
            "bearerAuth": [
              "ROLE_PARTNER"
            ]
          }
        ]
      }
    },
    "/partners/{partnerId}/users/{partnerUserId}/devices/{deviceId}/modules/{moduleId}/parameters": {
      "put": {
        "operationId": "putPartnerModuleParameters",
        "summary": "Update an partner module parameters",
        "tags": [
          "partners"
        ],
        "security": [
          {
            "bearerAuth": [
              "ROLE_PARTNER"
            ]
          }
        ]
      }
    },
    "/users/{userId}": {
      "get": {
        "operationId": "getUser",
        "summary": "Get a user's profile.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "put": {
        "operationId": "putUser",
        "summary": "Update a user's profile.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/guests": {
      "get": {
        "operationId": "getUserGuests",
        "summary": "Get a user's guests.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "post": {
        "operationId": "postUserGuest",
        "summary": "Create a user's guest.",
        "tags": [],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ]
      }
    },
    "/users/{userId}/guests/{guestId}": {
      "put": {
        "operationId": "putUserGuest",
        "summary": "Update a user's guest.",
        "tags": [],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteUserGuest",
        "summary": "Delete a user's guest.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/collaborators": {
      "get": {
        "operationId": "getUserCollaborators",
        "summary": "Get a user's collaborators.",
        "tags": [],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postUserCollaborator",
        "summary": "Create a user's collaborator.",
        "tags": [],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ]
      }
    },
    "/users/{userId}/collaborators/{collaboratorId}": {
      "put": {
        "operationId": "putUserCollaborator",
        "summary": "Update a user's collaborator.",
        "tags": [],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteUserCollaborator",
        "summary": "Delete a user's collaborator.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/aggregations": {
      "get": {
        "operationId": "getUserAggregations",
        "summary": "Get a user's aggregations.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "post": {
        "operationId": "postUserAggregation",
        "summary": "Create a user's aggregation.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/aggregations/{aggregationId}": {
      "get": {
        "operationId": "getUserAggregation",
        "summary": "Get a single user aggregation with statistics for graphs",
        "tags": [
          "cache"
        ],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ]
      },
      "put": {
        "operationId": "putUserAggregation",
        "summary": "Update a user's aggregation.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "delete": {
        "operationId": "deleteUserAggregation",
        "summary": "Delete a user's aggregation.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/deviceGroups": {
      "get": {
        "operationId": "getUserDeviceGroups",
        "summary": "Get a user's devices groups.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "post": {
        "operationId": "postUserDeviceGroup",
        "summary": "Create a user's device group.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/deviceGroups/{deviceGroupId}": {
      "get": {
        "operationId": "getUserDeviceGroup",
        "summary": "Get a user's devices group.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "put": {
        "operationId": "putUserDeviceGroup",
        "summary": "Update a user's device group.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "delete": {
        "operationId": "deleteUserDeviceGroup",
        "summary": "Delete a user's device group.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices": {
      "get": {
        "operationId": "getUserDevices",
        "summary": "Get a user's devices.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "post": {
        "operationId": "postUserDevice",
        "summary": "Setup a user's device.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/positions": {
      "get": {
        "operationId": "getUserDevicePositions",
        "summary": "Get a user's device geographic positions historic.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}": {
      "get": {
        "operationId": "getUserDevice",
        "summary": "Get a user's device.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "put": {
        "operationId": "putUserDevice",
        "summary": "Update a user's device.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "delete": {
        "operationId": "deleteUserDevice",
        "summary": "Delete a user's device access.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/modules": {
      "get": {
        "operationId": "getUserDeviceModules",
        "summary": "Get the modules a user activated on its device",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/modules/{moduleId}": {
      "put": {
        "operationId": "putUserDeviceModule",
        "summary": "Add a module to a user's device",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "delete": {
        "operationId": "deleteUserDeviceModule",
        "summary": "Disable a module for a user's device",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/shares/{sharesType}": {
      "put": {
        "operationId": "putUserDeviceShares",
        "summary": "Update a user's device shares.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/statistics": {
      "get": {
        "operationId": "getUserDeviceStatistics",
        "summary": "Get a user's device's device's statistics.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/data/raw": {
      "get": {
        "operationId": "getUserDeviceRawData",
        "summary": "Get a user's device's raw data.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/data/hourly": {
      "get": {
        "operationId": "getUserDeviceHourlyData",
        "summary": "Get a user's device's hourly data.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/data/daily": {
      "get": {
        "operationId": "getUserDeviceDailyData",
        "summary": "Get a user's device's daily data.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/countinuousStatistics": {
      "get": {
        "operationId": "getUserDeviceContinuousStatistics",
        "summary": "Get a user's device's continuous device's statistics.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/degreeDays": {
      "get": {
        "operationId": "getUserDeviceDegreeDays",
        "summary": "Get a user's device's degree days.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/summaries/{date}": {
      "get": {
        "operationId": "getUserDeviceSummary",
        "summary": "Get a user's device's summary at a given date.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/devices/{deviceId}/forecasts": {
      "get": {
        "operationId": "getUserDeviceForecasts",
        "summary": "Get a user's device's forecasts.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/forecasts": {
      "get": {
        "operationId": "getUserForecasts",
        "summary": "Get a user's forecasts.",
        "tags": [],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ]
      }
    },
    "/users/{userId}/data/daily": {
      "get": {
        "operationId": "getUserDailyData",
        "summary": "Get a user's daily data for a given geo location.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/data/hourly": {
      "get": {
        "operationId": "getUserHourlyData",
        "summary": "Get a user's hourly data for a given geo location.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/preferences": {
      "get": {
        "operationId": "getUserPreferences",
        "summary": "Get a user's preferences.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "put": {
        "operationId": "putUserPreferences",
        "summary": "Update a user's preferences.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/organisations/{organisationId}/operations": {
      "get": {
        "operationId": "getOrganisationOperations",
        "summary": "Get a organisation's operations.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "post": {
        "operationId": "postOrganisationOperation",
        "summary": "Create an organisation's operation.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/organisations/{organisationId}/operations/{operationId}": {
      "get": {
        "operationId": "getOrganisationOperation",
        "summary": "Retrieve an organisation's operation.",
        "parameters": [
          {
            "in": "path",
            "description": "The organisation id",
            "name": "organisationId",
            "type": "number",
            "pattern": "^[0-9]+$",
            "minimum": 1,
            "required": true
          },
          {
            "in": "path",
            "required": true,
            "description": "The operation id",
            "name": "operationId",
            "type": "number",
            "pattern": "^[0-9]+$",
            "minimum": 1
          },
          {
            "in": "header",
            "name": "Authorization",
            "description": "Authorization with Bearer mecanism",
            "type": "string",
            "required": true
          },
          {
            "in": "query",
            "name": "access_token",
            "description": "Access token in the query string",
            "type": "string"
          }
        ],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "put": {
        "operationId": "putOrganisationOperation",
        "summary": "Update an organisation's operation.",
        "parameters": [
          {
            "in": "path",
            "description": "The organisation id",
            "name": "organisationId",
            "type": "number",
            "pattern": "^[0-9]+$",
            "minimum": 1,
            "required": true
          },
          {
            "in": "path",
            "required": true,
            "description": "The operation id",
            "name": "operationId",
            "type": "number",
            "pattern": "^[0-9]+$",
            "minimum": 1
          },
          {
            "in": "body",
            "name": "body",
            "description": "The operation to update",
            "schema": {
              "$ref": "#/definitions/OperationItem"
            },
            "required": true
          },
          {
            "in": "header",
            "name": "Authorization",
            "description": "Authorization with Bearer mecanism",
            "type": "string",
            "required": true
          },
          {
            "in": "query",
            "name": "access_token",
            "description": "Access token in the query string",
            "type": "string"
          }
        ],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "delete": {
        "operationId": "deleteOrganisationOperation",
        "summary": "Delete an organisation's operation.",
        "parameters": [
          {
            "in": "path",
            "description": "The organisation id",
            "name": "organisationId",
            "type": "number",
            "pattern": "^[0-9]+$",
            "minimum": 1,
            "required": true
          },
          {
            "in": "path",
            "required": true,
            "description": "The operation id",
            "name": "operationId",
            "type": "number",
            "pattern": "^[0-9]+$",
            "minimum": 1
          },
          {
            "in": "header",
            "name": "Authorization",
            "description": "Authorization with Bearer mecanism",
            "type": "string",
            "required": true
          },
          {
            "in": "query",
            "name": "access_token",
            "description": "Access token in the query string",
            "type": "string"
          }
        ],
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/alerts": {
      "get": {
        "operationId": "getUserAlerts",
        "summary": "Get a user's alerts.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "post": {
        "operationId": "postUserAlert",
        "summary": "Create a user's alert.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/users/{userId}/alerts/{alertId}": {
      "put": {
        "operationId": "putUserAlert",
        "summary": "Update a user's alert.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      },
      "delete": {
        "operationId": "deleteUserAlert",
        "summary": "Delete a user's alert.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    },
    "/organisations": {
      "post": {
        "operationId": "postOrganisation",
        "summary": "Creates a new organisation.",
        "tags": []
      }
    },
    "/organisations/{organisationId}": {
      "put": {
        "operationId": "putOrganisation",
        "summary": "Update an organisation.",
        "security": [
          {
            "bearerAuth": [
              "ROLE_USER"
            ]
          }
        ],
        "tags": []
      }
    }
  },
  "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    },
    "bearerAuth": {
      "type": "bearer"
    }
  }
}